# Generated by Django 4.2.2 on 2023-06-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("height", models.IntegerField()),
            ],
            options={"db_table": "coords",},
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("img", models.BinaryField()),
            ],
            options={"db_table": "images",},
        ),
        migrations.CreateModel(
            name="PerevalAdded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("add_time", models.TimeField(auto_now_add=True)),
                ("raw_data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("pending", "На рассмотрении"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонен"),
                        ],
                        default="new",
                        max_length=15,
                    ),
                ),
                ("beauty_title", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("other_titles", models.TextField(blank=True, null=True)),
                ("connect", models.TextField(blank=True, null=True)),
                ("winter", models.CharField(default="", max_length=5)),
                ("spring", models.CharField(default="", max_length=5)),
                ("summer", models.CharField(default="", max_length=5)),
                ("autumn", models.CharField(default="", max_length=5)),
                (
                    "coords",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pereval.coords"
                    ),
                ),
            ],
            options={"db_table": "pereval_added",},
        ),
        migrations.CreateModel(
            name="PerevalAreas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_parent", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "pereval_areas",},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("mid_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={"db_table": "users",},
        ),
        migrations.CreateModel(
            name="PerevalImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pereval.images"
                    ),
                ),
                (
                    "pereval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pereval.perevaladded",
                    ),
                ),
            ],
            options={"db_table": "pereval_images",},
        ),
    ]
