# Generated by Django 4.2.2 on 2023-06-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pereval", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="perevaladded", name="raw_data",),
        migrations.AddField(
            model_name="images",
            name="pereval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="pereval.perevaladded",
            ),
        ),
        migrations.AddField(
            model_name="images",
            name="title",
            field=models.CharField(default="Заголовок", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="images", name="img", field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="perevaladded",
            name="coords",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pereval.coords",
            ),
        ),
        migrations.AlterField(
            model_name="perevalimages",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pereval.images",
            ),
        ),
    ]
