# Generated by Django 4.2.2 on 2023-06-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pereval", "0002_remove_perevaladded_raw_data_images_pereval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perevaladded",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pereval.users",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users", name="email", field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(name="PerevalImages",),
    ]
